version: "3.3"

services:
  # Development related
  test-sqlite:
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    build:
      dockerfile: docker/bookmark/Dockerfile
      context: .
    entrypoint: pytest
    volumes:
      - ./bookmark-service:/opt/code

  test-postgresql:
    env_file: environment.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    build:
      dockerfile: docker/bookmark/Dockerfile
      context: .
    entrypoint: pytest
    depends_on:
      - db
    volumes:
      - ./bookmark-service:/opt/code

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
      args:
        # These values should be in sync with environment
        # for development. If you change them, you'll
        # need to rebuild the container
        - POSTGRES_DB=bookmarks
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=pgpassword
        - POSTGRES_PORT=5432
    ports:
      - "5432"

  # Producion related
  server:
    env_file: environment.env
    image: bookmarks_server
    build:
      context: .
      dockerfile: docker/bookmark/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
